chain_width = 40
edition = "2021"
group_imports = "StdExternalCrate"
ignore = [ "mime_type" ]
imports_granularity = "Module"
imports_layout = "Horizontal"
max_width = 79
reorder_imports = true
use_small_heuristics = "Off"
