name: Release

permissions:
  contents: write

on:
  push:
    tags:
      - alpha**

jobs:
  tests:
    uses: ./.github/workflows/check.yml

  create-release:
    runs-on: ubuntu-latest
    needs: [tests]
    steps:
      - uses: actions/checkout@v5
      - name: Get current date
        run: echo "RELEASE_DATE=$(date +'%Y-%m-%d')" >> $GITHUB_ENV
      - uses: taiki-e/create-gh-release-action@v1
        with:
          # changelog: CHANGELOG.md
          prefix: alpha
          title: $tag [${{ env.RELEASE_DATE }}]
          token: ${{ secrets.GITHUB_TOKEN }}

  upload-assets:
    needs: create-release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Install stable toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1

      - name: Caching
        uses: Swatinem/rust-cache@v2
        with:
          cache-all-crates: true
          save-if: ${{ github.ref == 'refs/heads/master' }}
          cache-provider: "github"

      - uses: taiki-e/upload-rust-binary-action@v1
        with:
          bin: zxc
          archive: zxc-$tag
          checksum: sha256
          token: ${{ secrets.GITHUB_TOKEN }}
